### PR TITLE
Fixed the installation scipt

### PR DESCRIPTION
**Pull request by lprsd**
Detailed enhancements documented in the ubuntu2204py311-README.md within this PR

### CODE REVIEW

**Comment by saleh-mir** [comment]
Hey man, 

Thank you so much! This is great. However, could you remove the step for the Python Virtual Environment? The point of the script is to be used on a fresh installation, and it assumes that Jesse is the only thing the user is using, so a virtual environment is not needed for that.

**Comment by lprsd** [comment]
It is useful to keep the virtual environment setup because - 

- It prevents system Python/pip upgrades from breaking Jesse (which was the original issue that prompted this update).
- It enhances security by keeping system Python unmodified (upon which other Ubuntu systems can rely).
- Simplifies troubleshooting by providing explicit paths independent of system configurations (when in doubt, can always use /opt/jesse/bin/python3 explictly without having to worry about system path etc.). 

These benefits apply even on dedicated servers.
But feel free to sleep over it and confirm your preference later.

**Comment by saleh-mir** [comment]
You're making great points. Okay, just one question: with this setup, does the user have to run a command to enter Jesse's Python environment, or is it already loaded for them?

**Comment by lprsd** [comment]
The environment is automatically loaded for users - we add it to both .bashrc and .zshrc during installation, so it's ready to use immediately after logging in. No manual activation needed. They can still use /opt/jesse/bin/python3 explicitly if they want to, but won't need to for normal operation.

**Comment by lprsd** [comment]
1. FWIW, this same script likely will also work with Ubuntu 20.04 and 24.04 without any changes. (I have not tested it. But since we're not messing with system python and using venv for installation, it should work, subject to few considerations in (3) below)
2. I'm not a fan of force modifying system python, pip version. A lot of systems and processes on Ubuntu rely on the built-in Python. And they test it all on the bundled python. Forcing a different python default can put the burden of verifying system-wide functions on you.
3. Even though this would work on 24.04, some changes like deadsnake ppa are not required. I can create a new 24.04 script too.

**Comment by lprsd** [comment]
Created a single installation script for both ubuntu versions and verified it works well on them. Enhanced the script in many ways.

**Comment by saleh-mir** [comment]
running ubuntu.sh I get this error:
```
root@dev:~# source <(curl -fsSL https://raw.githubusercontent.com/jesse-ai/stack-installer/37b39677a58ae72a70f8e5522fbfd874e170c0a6/ubuntu.sh)
[INFO] 2024-11-29 16:06:19 - Detected Ubuntu version: 22.04
[INFO] 2024-11-29 16:06:19 - Updating Ubuntu system packages...
Reading package lists...
E: Could not get lock /var/lib/apt/lists/lock. It is held by process 10399 (apt-get)
E: Unable to lock directory /var/lib/apt/lists/
[ERROR] 2024-11-29 16:06:21 - Failed to update package list
Check the logs at /var/log/jesse/jesse_install.log for details
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.
[ERROR] 2024-11-29 16:06:21 - Failed to upgrade packages
Check the logs at /var/log/jesse/jesse_install.log for details
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.
[ERROR] 2024-11-29 16:06:21 - Failed to perform distribution upgrade
Check the logs at /var/log/jesse/jesse_install.log for details
[INFO] 2024-11-29 16:06:21 - Installing basic dependencies...
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.
[ERROR] 2024-11-29 16:06:21 - Failed to install build essentials
Check the logs at /var/log/jesse/jesse_install.log for details
[INFO] 2024-11-29 16:06:21 - Installing Python 3.11...
Reading package lists...
E: Could not get lock /var/lib/apt/lists/lock. It is held by process 10858 (apt-get)
E: Unable to lock directory /var/lib/apt/lists/
Repository: 'deb https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu/ jammy main'
Description:
This PPA contains more recent Python versions packaged for Ubuntu.

Disclaimer: there's no guarantee of timely updates in case of security problems or other issues. If you want to use them in a security-or-otherwise-critical environment (say, on a production server), you do so at your own risk.

Update Note
===========
Please use this repository instead of ppa:fkrull/deadsnakes.

Reporting Issues
================

Issues can be reported in the master issue tracker at:
https://github.com/deadsnakes/issues/issues

Supported Ubuntu and Python Versions
====================================

- Ubuntu 20.04 (focal) Python3.5 - Python3.7, Python3.9 - Python3.13
- Ubuntu 22.04 (jammy) Python3.7 - Python3.9, Python3.11 - Python3.13
- Ubuntu 24.04 (noble) Python3.7 - Python3.11, Python3.13
- Note: Python2.7 (focal, jammy), Python 3.8 (focal), Python 3.10 (jammy), Python3.12 (noble) are not provided by deadsnakes as upstream ubuntu provides those packages.

Why some packages aren't built:
- Note: for focal, older python versions require libssl<1.1 so they are not currently built
- Note: for jammy and noble, older python versions requre libssl<3 so they are not currently built
- If you need these, reach out to asottile to set up a private ppa

The packages may also work on other versions of Ubuntu or Debian, but that is not tested or supported.

Packages
========

The packages provided here are loosely based on the debian upstream packages with some modifications to make them more usable as non-default pythons and on ubuntu.  As such, the packages follow debian's patterns and often do not include a full python distribution with just `apt install python#.#`.  Here is a list of packages that may be useful along with the default install:

- `python#.#-dev`: includes development headers for building C extensions
- `python#.#-venv`: provides the standard library `venv` module
- `python#.#-distutils`: provides the standard library `distutils` module
- `python#.#-lib2to3`: provides the `2to3-#.#` utility as well as the standard library `lib2to3` module
- `python#.#-gdbm`: provides the standard library `dbm.gnu` module
- `python#.#-tk`: provides the standard library `tkinter` module

Third-Party Python Modules
==========================

Python modules in the official Ubuntu repositories are packaged to work with the Python interpreters from the official repositories. Accordingly, they generally won't work with the Python interpreters from this PPA. As an exception, pure-Python modules for Python 3 will work, but any compiled extension modules won't.

To install 3rd-party Python modules, you should use the common Python packaging tools.  For an introduction into the Python packaging ecosystem and its tools, refer to the Python Packaging User Guide:
https://packaging.python.org/installing/

Sources
=======
The package sources are available at:
https://github.com/deadsnakes/

Nightly Builds
==============

For nightly builds, see ppa:deadsnakes/nightly https://launchpad.net/~deadsnakes/+archive/ubuntu/nightly
More info: https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa
Adding repository.
Found existing deb entry in /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list
Adding deb entry to /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list
Found existing deb-src entry in /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list
Adding key to /etc/apt/trusted.gpg.d/deadsnakes-ubuntu-ppa.gpg with fingerprint F23C5A6CF475977595C89F51BA6932366A755776
Reading package lists...
E: Could not get lock /var/lib/apt/lists/lock. It is held by process 10858 (apt-get)
E: Unable to lock directory /var/lib/apt/lists/
[ERROR] 2024-11-29 16:06:28 - Failed to update after adding Python repository
Check the logs at /var/log/jesse/jesse_install.log for details
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.
[ERROR] 2024-11-29 16:06:28 - Failed to install Python
Check the logs at /var/log/jesse/jesse_install.log for details
Command 'python3.11' not found, but can be installed with:
apt install python3.11
[ERROR] 2024-11-29 16:06:28 - Script failed on line 61
[ERROR] 2024-11-29 16:06:28 - Script failed on line 117
Connection to 91.107.203.89 closed.
```

**Comment by lprsd** [comment]
The error shows there are multiple issues, but they can be fixed in sequence. Before running the installation script again, you need to:

1. First, fix the dpkg interrupted state:
```bash
dpkg --configure -a
```

2. Then, release the apt lock (if any process is still holding it):
```bash
killall apt-get
rm /var/lib/apt/lists/lock
rm /var/lib/dpkg/lock*
rm /var/cache/apt/archives/lock
```

3. After that, update apt:
```bash
apt-get update
```

Once these are done, try running the installation script again. Let me know if you need any clarification or encounter other issues.

**Comment by saleh-mir** [comment]
Thank you, that worked. 

Does that mean we need to add the `apt-get update` in the beginning of the script? Correct me if I'm wrong, but now that the Ubuntu.sh script works for both versions, we do not need that other script you added, right?

**Comment by lprsd** [comment]
Right.

- Let's assume the version you had was v1.
- The ubuntu2204py311.sh can be considered v1.1 which fixed the specific issue for the specific platform, with no major changes, only minor enhancement.
- The ubuntu.sh file can be considered v2, which just took the steps from the original script and Claude added a bunch of best practices like logging, checking etc. and to be used for both 2204 and 2404.
- I included both. But if v2 works well, and you're satisfied, no need for v1, I guess.
- Also, yes. `apt-get update` would be useful at the start. Let me add it.

**Pull request merged**
